import { BemusterungsArtikel } from "../types";

const bemusterungsArtikel: BemusterungsArtikel[] = [
  {
    kategorie: "Flooring",
    ausgeblendet: false,
    bezeichnung: "Product A - Flooring Type 1",
    artNr: "100001",
    preis: 11,
    bildDateiName: null,
  },
  {
    kategorie: "Flooring",
    ausgeblendet: false,
    bezeichnung: "Product B - Flooring Type 2",
    artNr: "100002",
    preis: 0,
    bildDateiName: null,
  },
  {
    kategorie: "Flooring",
    ausgeblendet: false,
    bezeichnung: "Product C - Flooring Type 3",
    artNr: "100003",
    preis: 26,
    bildDateiName: null,
  },
  {
    kategorie: "Tiles",
    ausgeblendet: false,
    bezeichnung: "Tile Type 1 - Urban White",
    artNr: "TILE001",
    preis: 0,
    bildDateiName: null,
  },
  {
    kategorie: "Tiles",
    ausgeblendet: false,
    bezeichnung: "Tile Type 2 - Urban Grey",
    artNr: "TILE002",
    preis: 60,
    bildDateiName: null,
  },
  {
    kategorie: "Sanitary",
    ausgeblendet: false,
    serie: "Series A",
    fuerBadTyp: ["duschbad"],
    bezeichnung: "Sanitary Set A",
    artNr: "SAN001",
    preis: 2000,
    bildDateiName: null,
  },
  {
    kategorie: "Sanitary",
    ausgeblendet: false,
    serie: "Series B",
    fuerBadTyp: ["gästewc"],
    bezeichnung: "Sanitary Set B",
    artNr: "SAN002",
    preis: 1000,
    bildDateiName: null,
  },
  {
    kategorie: "Faucets",
    ausgeblendet: false,
    serie: "Modern Line",
    fuerBadTyp: ["wannenbad"],
    bezeichnung: "Faucet Type A",
    artNr: "FAC001",
    preis: 350,
    bildDateiName: null,
  },
  {
    kategorie: "Electrics",
    ausgeblendet: false,
    bezeichnung: "Additional Power Outlet",
    preis: 155,
    bildDateiName: "PowerOutlet.png",
  },
  {
    kategorie: "Electrics",
    ausgeblendet: false,
    bezeichnung: "Additional Light Switch",
    preis: 110,
    bildDateiName: "LightSwitch.png",
  },
  {
    kategorie: "Heating",
    ausgeblendet: false,
    bezeichnung: "Towel Warmer - Electric",
    preis: 600,
    bildDateiName: null,
  },
];

const apartments = [
  {
    id: "0",
    projectId: "0",
    angebotsname: "C / 05",
    erwerber: "Frau Max Mustermann",
    angebotsdatum: new Date("2023-06-14"),
    name: "Apartment 1",
    wohnFlaeche: 97,
    stockwerk: "EG",
    raeumeMitFliesen: [
      { roomType: "roomType0", bodenFlaeche: 15, wandFlaeche: 16 },
    ],
    raeumeMitParkett: [{ roomType: "roomType8", parkettArtNr: "15940160" }],
    wohnFlaecheParkett: 102.43,
  },
  {
    id: "1",
    angebotsname: "C / 06",
    erwerber: "Herr Friedrich Müller",
    angebotsdatum: new Date("2023-07-08"),
    name: "Apartment 2",
    wohnFlaeche: 140,
    stockwerk: "EG",
    raeumeMitFliesen: [
      { roomType: "roomType1", bodenFlaeche: 15, wandFlaeche: 16 },
      { roomType: "roomType0", bodenFlaeche: 15, wandFlaeche: 16 },
    ],
    wohnFlaecheParkett: 102.43,
  },
  {
    id: "2",
    angebotsname: "C / 07",
    erwerber: "Frau Maria Musterfrau",
    angebotsdatum: new Date("2023-08-22"),
    name: "Apartment 3",
    wohnFlaeche: 105,
    stockwerk: "1. Stock",
    raeumeMitFliesen: [
      { roomType: "roomType2", bodenFlaeche: 15, wandFlaeche: 16 },
    ],
    wohnFlaecheParkett: 102.43,
  },
  {
    id: "3",
    angebotsname: "C / 08",
    erwerber: "Herr Daniel Düsentrieb",
    angebotsdatum: new Date("2023-09-12"),
    name: "Apartment 4",
    wohnFlaeche: 75,
    stockwerk: "DG",
    raeumeMitFliesen: [
      { roomType: "roomType3", bodenFlaeche: 15, wandFlaeche: 16 },
    ],
    wohnFlaecheParkett: 102.43,
  },
  {
    id: "4",
    angebotsname: "C / 14",
    erwerber: "Frau Daniela Meier",
    angebotsdatum: new Date("2023-10-01"),
    name: "Apartment 5",
    wohnFlaeche: 105,
    stockwerk: "1. Stock",
    raeumeMitFliesen: [
      { roomType: "roomType3", bodenFlaeche: 15, wandFlaeche: 16 },
    ],
    wohnFlaecheParkett: 102.43,
  },
  {
    id: "5",
    angebotsname: "C / 15",
    erwerber: "Frau Gabriele Müller",
    angebotsdatum: new Date("2023-11-22"),
    name: "Apartment 6",
    wohnFlaeche: 105,
    stockwerk: "1. Stock",
    raeumeMitFliesen: [
      { roomType: "roomType3", bodenFlaeche: 15, wandFlaeche: 16 },
    ],
    wohnFlaecheParkett: 102.43,
  },
  {
    id: "6",
    angebotsname: "C / 16",
    erwerber: "Herr Stefan Schneider",
    angebotsdatum: new Date("2023-12-12"),
    name: "Apartment 7",
    wohnFlaeche: 105,
    stockwerk: "1. Stock",
    raeumeMitFliesen: [
      { roomType: "roomType3", bodenFlaeche: 15, wandFlaeche: 16 },
    ],
    wohnFlaecheParkett: 102.43,
  },
  {
    id: "7",
    angebotsname: "C / 17",
    erwerber: "Herr Fred Feuerstein",
    angebotsdatum: new Date("2024-01-01"),
    name: "Apartment 8",
    wohnFlaeche: 105,
    stockwerk: "1. Stock",
    raeumeMitFliesen: [
      { roomType: "roomType3", bodenFlaeche: 15, wandFlaeche: 16 },
    ],
    wohnFlaecheParkett: 102.43,
  },
  {
    id: "8",
    angebotsname: "C / 34",
    erwerber: "Frau Wilma Feuerstein",
    angebotsdatum: new Date("2024-02-22"),
    name: "Apartment 9",
    wohnFlaeche: 105,
    stockwerk: "1. Stock",
    raeumeMitFliesen: [
      { roomType: "roomType3", bodenFlaeche: 15, wandFlaeche: 16 },
    ],
    wohnFlaecheParkett: 102.43,
  },
  {
    id: "9",
    angebotsname: "C / 35",
    erwerber: "Herr Barney Geröllheimer",
    angebotsdatum: new Date("2024-03-12"),
    name: "Apartment 10",
    wohnFlaeche: 105,
    stockwerk: "1. Stock",
    raeumeMitFliesen: [
      { roomType: "roomType3", bodenFlaeche: 15, wandFlaeche: 16 },
    ],
    wohnFlaecheParkett: 102.43,
  },
  {
    id: "10",
    angebotsname: "C / 36",
    erwerber: "Herr Luke Skywalker",
    angebotsdatum: new Date("2024-04-01"),
    name: "Apartment 11",
    wohnFlaeche: 105,
    stockwerk: "1. Stock",
    raeumeMitFliesen: [
      { roomType: "roomType3", bodenFlaeche: 15, wandFlaeche: 16 },
    ],
    wohnFlaecheParkett: 102.43,
  },
  {
    id: "11",
    angebotsname: "C / 37",
    erwerber: "Frau Leia Organa",
    angebotsdatum: new Date("2024-05-22"),
    name: "Apartment 12",
    wohnFlaeche: 105,
    stockwerk: "1. Stock",
    raeumeMitFliesen: [
      { roomType: "roomType3", bodenFlaeche: 15, wandFlaeche: 16 },
    ],
    wohnFlaecheParkett: 102.43,
  },
  {
    id: "12",
    angebotsname: "C / 38",
    erwerber: "Herr Han Solo",
    angebotsdatum: new Date("2024-06-12"),
    name: "Apartment 13",
    wohnFlaeche: 105,
    stockwerk: "1. Stock",
    raeumeMitFliesen: [
      { roomType: "roomType3", bodenFlaeche: 15, wandFlaeche: 16 },
    ],
    wohnFlaecheParkett: 102.43,
  },
  {
    id: "13",
    angebotsname: "C / 39",
    erwerber: "Herr Chewbacca",
    angebotsdatum: new Date("2024-07-01"),
    name: "Apartment 14",
    wohnFlaeche: 105,
    stockwerk: "1. Stock",
    raeumeMitFliesen: [
      { roomType: "roomType3", bodenFlaeche: 15, wandFlaeche: 16 },
    ],
    wohnFlaecheParkett: 102.43,
  },
  {
    id: "14",
    angebotsname: "C / 40",
    erwerber: "Herr Yoda",
    angebotsdatum: new Date("2024-08-22"),
    name: "Apartment 15",
    wohnFlaeche: 105,
    stockwerk: "1. Stock",
    raeumeMitFliesen: [
      { roomType: "roomType3", bodenFlaeche: 15, wandFlaeche: 16 },
    ],
    wohnFlaecheParkett: 102.43,
  },
  {
    id: "15",
    angebotsname: "C / 41",
    erwerber: "Herr Obi Wan Kenobi",
    angebotsdatum: new Date("2024-09-12"),
    name: "Apartment 16",
    wohnFlaeche: 105,
    stockwerk: "1. Stock",
    raeumeMitFliesen: [
      { roomType: "roomType3", bodenFlaeche: 15, wandFlaeche: 16 },
    ],
    wohnFlaecheParkett: 102.43,
  },
  {
    id: "16",
    angebotsname: "C / 42",
    erwerber: "Herr Darth Vader",
    angebotsdatum: new Date("2024-10-01"),
    name: "Apartment 17",
    wohnFlaeche: 105,
    stockwerk: "1. Stock",
    raeumeMitFliesen: [
      { roomType: "roomType3", bodenFlaeche: 15, wandFlaeche: 16 },
    ],
    wohnFlaecheParkett: 102.43,
  },
  {
    id: "17",
    angebotsname: "C / 43",
    erwerber: "Herr C3PO",
    angebotsdatum: new Date("2024-11-22"),
    name: "Apartment 18",
    wohnFlaeche: 105,
    stockwerk: "1. Stock",
    raeumeMitFliesen: [
      { roomType: "roomType3", bodenFlaeche: 15, wandFlaeche: 16 },
    ],
    wohnFlaecheParkett: 102.43,
  },
  {
    id: "18",
    angebotsname: "C / 44",
    erwerber: "Herr R2D2",
    angebotsdatum: new Date("2024-12-12"),
    name: "Apartment 19",
    wohnFlaeche: 105,
    stockwerk: "1. Stock",
    raeumeMitFliesen: [
      { roomType: "roomType3", bodenFlaeche: 15, wandFlaeche: 16 },
    ],
    wohnFlaecheParkett: 102.43,
  },
  {
    id: "19",
    angebotsname: "C / 45",
    erwerber: "Herr Lando Calrissian",
    angebotsdatum: new Date("2025-01-01"),
    name: "Apartment 20",
    wohnFlaeche: 105,
    stockwerk: "1. Stock",
    raeumeMitFliesen: [
      { roomType: "roomType3", bodenFlaeche: 15, wandFlaeche: 16 },
    ],
    wohnFlaecheParkett: 102.43,
  },
  {
    id: "20",
    angebotsname: "C / 46",
    erwerber: "Herr Jabba the Hutt",
    angebotsdatum: new Date("2025-02-22"),
    name: "Apartment 21",
    wohnFlaeche: 105,
    stockwerk: "1. Stock",
    raeumeMitFliesen: [
      { roomType: "roomType3", bodenFlaeche: 15, wandFlaeche: 16 },
    ],
    wohnFlaecheParkett: 102.43,
  },
  {
    id: "21",
    angebotsname: "C / 47",
    erwerber: "Herr jar jar Binks",
    angebotsdatum: new Date("2025-03-12"),
    name: "Apartment 22",
    wohnFlaeche: 105,
    stockwerk: "1. Stock",
    raeumeMitFliesen: [
      { roomType: "roomType3", bodenFlaeche: 15, wandFlaeche: 16 },
    ],
    wohnFlaecheParkett: 102.43,
  },
  {
    id: "22",
    angebotsname: "C / 48",
    erwerber: "Herr Boba Fett",
    angebotsdatum: new Date("2025-04-01"),
    name: "Apartment 23",
    wohnFlaeche: 105,
    stockwerk: "1. Stock",
    raeumeMitFliesen: [
      { roomType: "roomType3", bodenFlaeche: 15, wandFlaeche: 16 },
    ],
    wohnFlaecheParkett: 102.43,
  },
  {
    id: "23",
    angebotsname: "C / 49",
    erwerber: "Herr Raumschiff Enterprise",
    angebotsdatum: new Date("2025-05-22"),
    name: "Apartment 24",
    wohnFlaeche: 105,
    stockwerk: "1. Stock",
    raeumeMitFliesen: [
      { roomType: "roomType3", bodenFlaeche: 15, wandFlaeche: 16 },
    ],
    wohnFlaecheParkett: 102.43,
  },
];

const projects = [
  {
    name: "Large Project (very slow)",
    created_at: new Date("2024-09-22"),
    bauleiter: "manager1",
    apartments: apartments,
    bemusterungs_artikel: bemusterungsArtikel,
  },
  {
    name: "Small Project (not fast, but okay)",
    created_at: new Date("2024-09-12"),
    bauleiter: "manager1",
    apartments: [
      {
        id: "0",
        projectId: "1",
        angebotsname: "Offer / 87",
        erwerber: "Client 1",
        angebotsdatum: new Date("2023-06-14"),
        name: "Apartment 1",
        wohnFlaeche: 92,
        wohnFlaecheParkett: 98,
        stockwerk: "Top Floor",
        raeumeMitFliesen: [
          {
            roomType: "Tile Room 1",
            bodenFlaeche: 1,
            wandFlaeche: 2,
          },
        ],
      },
    ],
    bemusterungs_artikel: bemusterungsArtikel,
  },
];

const pdfData = {
  angebotsnummer: "offer / XX/XXX",
  angebotsdatum: new Date().toLocaleDateString(),
  Apartment: "Apartment /XX",
  erwerber: "Client 2",
  produkte: [
    {
      kategorie: "Category 1",
      raumTyp: "Bathroom",
      bild: "/assets/0.png",
      titel: "Product A",
      beschreibung: "Description A",
      anzahl: 1,
      preis: 1500,
    },
    {
      kategorie: "Category 1",
      raumTyp: "Bathroom",
      bild: "/assets/1.png",
      titel: "Product B",
      beschreibung: "Description B",
      anzahl: 1,
      preis: 700,
    },
    {
      kategorie: "Category 2",
      raumTyp: "Bathroom",
      bild: "/assets/2.png",
      titel: "Product C",
      beschreibung: "Description C",
      anzahl: 50,
      preis: 20,
    },
    {
      kategorie: "Category 2",
      raumTyp: "Bathroom",
      bild: "/assets/3.png",
      titel: "Product D",
      beschreibung: "Description D",
      anzahl: 25,
      preis: 15,
    },
    {
      kategorie: "Category 3",
      raumTyp: "Entire Apartment",
      bild: "/assets/4.png",
      titel: "Product E",
      beschreibung: "Description E",
      anzahl: 100,
      preis: 10,
    },
    {
      kategorie: "Category 3",
      raumTyp: "Entire Apartment",
      bild: "/assets/5.png",
      titel: "Product F",
      beschreibung: "Description F",
      anzahl: 250,
      preis: 35,
    },
  ],
};

export default {
  projects,
  bemusterungsArtikel,
  pdfData,
  apartments,
};
